# Flight Tracker Collector Configuration
# Environment variables: ${VAR_NAME:-default_value}

# Global settings
global:
  redis:
    host: ${REDIS_HOST:-localhost}
    port: ${REDIS_PORT:-6379}
    db: ${REDIS_DB:-0}
    key_expiry: 3600  # 1 hour TTL for flight data
  
  logging:
    level: ${LOG_LEVEL:-INFO}
    file: logs/flight_collector.log
    rotate_time: "00:00"  # Midnight local time
    backup_count: 7  # Keep 7 days of logs
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  polling:
    default_interval: 30  # seconds
    retry_attempts: 3
    timeout: 10
    backoff_factor: 2  # Exponential backoff multiplier

# Region definitions
regions:
  socal:
    enabled: true
    name: "Southern California"
    timezone: "America/Los_Angeles"
    center:
      lat: 34.0522  # Los Angeles
      lon: -118.2437
    radius_miles: 150
    collectors:
      - type: "opensky"
        enabled: true
        url: "https://opensky-network.org/api/states/all"
        anonymous: ${OPENSKY_ANONYMOUS:-true}
        username: ${OPENSKY_USERNAME:-}
        password: ${OPENSKY_PASSWORD:-}
        
      - type: "dump1090"
        enabled: true
        url: "http://192.168.1.100:8080/data/aircraft.json"
        name: "LAX Area Receiver"
  
  bayarea:
    enabled: true
    name: "San Francisco Bay Area"
    timezone: "America/Los_Angeles"
    center:
      lat: 37.7749  # San Francisco
      lon: -122.4194
    radius_miles: 100
    collectors:
      - type: "opensky"
        enabled: true
        url: "https://opensky-network.org/api/states/all"
        anonymous: true
        
      - type: "dump1090"
        enabled: true
        url: "http://10.0.0.50:8080/data/aircraft.json"
        name: "SFO Area Receiver"

  phoenix:
    enabled: true
    name: "Phoenix Metro"
    timezone: "America/Phoenix"
    center:
      lat: 33.4484  # Phoenix
      lon: -112.0740
    radius_miles: 80
    collectors:
      - type: "dump1090"
        enabled: true
        url: "http://10.0.1.20:8080/data/aircraft.json"
        name: "PHX Area Receiver"

# Airport database for destination estimation
airports:
  # California
  LAX:
    name: "Los Angeles International"
    lat: 33.9425
    lon: -118.4081
    icao: "KLAX"
    
  SFO:
    name: "San Francisco International"
    lat: 37.6213
    lon: -122.3790
    icao: "KSFO"
    
  SAN:
    name: "San Diego International"
    lat: 32.7338
    lon: -117.1933
    icao: "KSAN"
    
  OAK:
    name: "Oakland International"
    lat: 37.7213
    lon: -122.2207
    icao: "KOAK"
    
  SJC:
    name: "San Jose International"
    lat: 37.3639
    lon: -121.9289
    icao: "KSJC"
    
  BUR:
    name: "Bob Hope Airport"
    lat: 34.2007
    lon: -118.3590
    icao: "KBUR"
    
  # Nevada
  LAS:
    name: "Las Vegas McCarran"
    lat: 36.0840
    lon: -115.1537
    icao: "KLAS"
    
  # Arizona
  PHX:
    name: "Phoenix Sky Harbor"
    lat: 33.4352
    lon: -112.0101
    icao: "KPHX"
    
  TUS:
    name: "Tucson International"
    lat: 32.1161
    lon: -110.9410
    icao: "KTUS"

# Collector type definitions
collector_types:
  opensky:
    class: "OpenSkyCollector"
    rate_limit: 100  # requests per minute
    daily_credits_anonymous: 400
    daily_credits_authenticated: 4000
    credit_header: "X-Rate-Limit-Remaining"
    
  dump1090:
    class: "Dump1090Collector"
    rate_limit: 600  # 10 requests per second
    local: true  # No external rate limiting

# Helicopter identification patterns
helicopter_patterns:
  # Medical helicopters
  - prefix: "N911"
  - prefix: "LIFE"
  - callsign_contains: ["MEDIC", "ANGEL", "STAR", "LIFE"]
  
  # Law enforcement
  - prefix: "N120LA"  # LAPD pattern
  - prefix: "N220LA"
  - callsign_contains: ["POLICE", "SHERIFF"]
  
  # News helicopters
  - callsign_contains: ["NEWS", "SKY", "CHOPPER"]
  
  # Military patterns
  - icao_hex_prefix: ["AE"]  # US Military
  
  # General helicopter models (ICAO type codes)
  - aircraft_type: ["H60", "EC30", "EC35", "EC45", "B407", "B429", "AS50", "R44", "R66"]